#configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://database-1.cby8gwqkq37r.us-east-2.rds.amazonaws.com/TC_Prototype
#spring.datasource.url=jdbc:mysql://127.0.0.1/TopClass
spring.datasource.username=admin
spring.datasource.password=TopClassCSUSM2024
#spring.datasource.username=root
#spring.datasource.password=2318153Rr

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver